language: cpp
sudo: required
cache: ccache

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env: BUILD_DOXYGEN=false QT_BASE="qt57" QT_PPA="ppa:beineri/opt-qt57-trusty"
  fast_finish: true

before_install:
  - sudo add-apt-repository "${QT_PPA}" -y && sudo apt-get update -qq

install:
  - sudo apt-get install -qq libglu1-mesa-dev xvfb
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  - sudo apt-get install -qq "${QT_BASE}base" "${QT_BASE}tools"; source "/opt/${QT_BASE}/bin/${QT_BASE}-env.sh"

script:
  - mkdir build && cd build && qmake PREFIX=/app ../librepcb.pro -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j8 && cd ../   # build librepcb
  - cd build && sudo make install && cd ../
  - sudo wget "https://github.com/probonopd/linuxdeployqt/releases/download/1/linuxdeployqt-1-x86_64.AppImage" -O /usr/local/bin/linuxdeployqt
  - sudo chmod a+x /usr/local/bin/linuxdeployqt
  - find /app
  - linuxdeployqt /app/bin/librepcb -appimage || true
  - find /app
